language: node_js
node_js:
- '6'
- '7'

before_install:
- export TZ=Europe/Zurich

script: npm test

after_script: npm install coveralls@^2.11.9 && cat ./coverage/lcov-mapped.info | coveralls

deploy:
  provider: npm
  email: christoph.buehler@bluewin.ch
  api_key:
    secure: MC4hvqn8I8jka1VFaQGZCSl+qofZyycehLauwSxpMpoJWC45DbGfAo/AcI8WrPcG0dqpdd9lTJ6wep92fWRAPerBrJ48W8uHps97kfgc/NTRfQGv0eGq8gmDadMI7iA3r5gHkuqyW0R91/tpY/zEc9YwoC669u4oCUhV5fpW/KU6j2J4jskTH00ZBiGkkAjjKPyfJJbmsEWO8kHbL2Idn1pberdjkAYtvK+VmzN/JvGf3c4B+bQ4ixFrVXGOubbf/ri5H5YzfQqOjA7Ifkls2KFkW8KRFmq7/9ou69iEwiFnI+ZkjWn8OOrC2g9wFcdHHjeA6NPDdix5njPc2jolmk1Wd3s6QLA479eTMui5d3WYyM3zDnyGCJRWLYGzfYZiUu6dlh2okzx6Xd/bk+G4UxIjaFs4Y70jaUrwjPPhuB4/+9oFbkuApeVBQf6FWhGws6p4BFTgEHxGVIn0x3xGI7+SbOl0DDnVJzynOhRI168/Q+nsOuY21Qiz59t7YSbUbLCNq+Krxmh9FDtqxL1B0ztXIZuCKJ49VT+2Oh5KkYhICmL3EapIyOPD+nBl7/eyAoxlhUgsAM+UpgbvQ1kkmf5CqieB7K53MADfZz+FQ1Pmbz0zny8whtk3iIFec0a4mXtuQsAlCA4sk4yDjNUjl1uX87KdGXEVOgmm5I9tXB8=
  on:
    tags: true
    repo: buehler/ts-json-serializer

notifications:
  email: false
  slack:
    on_success: never
    on_failure: always
    secure: GzU21HzYdaiC08KhkfCTFkp7jZN9ByihaPrDnA5O51C4v8FsS6cPmdSBkSu67xlUq8L6hVFdkFoTmX9PClg+v4SLD2/uQC5ICfnlbLj91duAF02GPrWQrmaemfhdAbcGxgSli3VquQWVuZGXppNfo8XDkObdB9k/yOlbEc09s+TPUcxhtmFfwXrFxNjkJHayXO+kPrNnIAd51AvKjiVMxP16jtp1D1tJNSaz7t5FJaj2mhE/n7f/lT23tIky/p7bMLyEaxPkMqfm4Z8QKrphvq94V2AxzpiXtG1AYg+1V7PjxN0HoLy82RPXy7OFKMNasifudGEljwhCE1EKQTNOMNmMuesAAIrfnF+lTcI7Z3b7olmA1ydnQX3VSfdPBqsUgPNvkGCKBVzs36vsE2Qo7aXkWvGprwBNKLEV62IjHmwjx+lz5qAgGJYdN+gnCSKkFFb9iWtPq0vpipLq+cjZ8OZsK0HVnhKf7frAjnpuL1pTqWV/6AAp21ySpMj05xr6vuOChwsJaSyFcLvxoe4HOTP5kefBGNn1uTyqW9oU3ax+G+ESbWUaG2+3i/MQ/Cc7h9R6p5730SyGwt55xUmfIiA1vuMQCwrV2KrDfMteXRxyDiHzxa+dtDKcsx+yrbXIQpxgQu+zwdsPhQtHcATMhVclGpqbJ15tgbzBKcDHunI=
